#!venv/bin/python -u
'Program to schedule control of Watts Clever switches.'
# Requires python 3.4+
# Mark Blakeney, May 2016.

# Standard packages
import os
import sys
import argparse
import threading
from pathlib import Path

# 3rd party packages
import ruamel.yaml as yaml

# Local packages
import scheduler
import web

# Process command line options
opt = argparse.ArgumentParser(description=__doc__.strip())
opt.add_argument('-c', '--config',
        help='alternative configuration file')
args = opt.parse_args()

# Determine config file path
cfile = Path(args.config) if args.config else \
        Path(os.getenv('XDG_CONFIG_HOME', '~/.config')).expanduser() / \
        (opt.prog + '.conf')

# Open and read config file
with cfile.open() as fp:
    conf = yaml.safe_load(fp)

num_timers, num_hooks = scheduler.init(args, conf)
print('Starting with {} timers, {} webhooks'.format(num_timers, num_hooks))

# We always run the web server in main thread because better for
# interrupt (e.g. ctrl+c) handling
if num_hooks > 0 and web.init(args, conf):
    if num_timers > 0:
        t = threading.Thread(target=scheduler.run)
        t.daemon = True
        t.start()

    web.run()
else:
    if num_timers == 0:
        sys.exit('Terminating because nothing to do ..')

    scheduler.run()
